# frozen_string_literal: true

require_relative 'core/base_x'
require_relative 'core/base_58_xrp'
require_relative 'core/core'
require_relative 'core/utilities'

require_relative 'address-codec/codec'
require_relative 'address-codec/xrp_codec'
require_relative 'address-codec/address_codec'

require_relative 'binary-codec/enums/constants'
require_relative 'binary-codec/utilities'
require_relative 'binary-codec/enums/fields'
require_relative 'binary-codec/enums/definitions'
require_relative 'binary-codec/serdes/binary_parser'
require_relative 'binary-codec/serdes/bytes_list'
require_relative 'binary-codec/serdes/binary_serializer'
require_relative 'binary-codec/types/serialized_type'
require_relative 'binary-codec/types/hash'
require_relative 'binary-codec/types/uint'
require_relative 'binary-codec/types/account_id'
require_relative 'binary-codec/types/amount'
require_relative 'binary-codec/types/blob'
require_relative 'binary-codec/types/currency'
require_relative 'binary-codec/types/st_array'
require_relative 'binary-codec/types/st_object'
require_relative 'binary-codec/types/vector256'
require_relative 'binary-codec/types/path_set'
require_relative 'binary-codec/types/issue'
require_relative 'binary-codec/types/xchain_bridge'
require_relative 'binary-codec/binary_codec'

require_relative 'wallet/wallet'

require_relative 'key-pairs/ed25519'
require_relative 'key-pairs/secp256k1'
require_relative 'key-pairs/key_pairs'